apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-nginx
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/demo-nginx/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: azure-hybrid-boilerplate
  targetNamespace: demo
