apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system                 
  - demo-nginx-kustomization.yaml
  - monitoring-kustomization.yaml
  - pihole-kustomization.yaml

