apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system                 # bootstrapâ€™s own stuff
  - demo-nginx-kustomization.yaml
  # later: tailscale-operator-kustomization.yaml, infra, etc.
